apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techmart-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/techmart-frontend.git
    targetRevision: HEAD
    path: kubernetes/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: techmart-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
